# Generated by Django 6.0.4 on 2026-05-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img_src',
            field=models.URLField(blank=True, null=True),
        ),
    ]
