# Generated by Django 6.0.4 on 2026-05-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_img_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_src',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
