# Generated by Django 6.0.4 on 2026-05-02 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_img_src'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='img_src',
            new_name='image',
        ),
    ]
