# Generated by Django 6.0.4 on 2026-05-03 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_img_src_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='student_number',
        ),
    ]
