# Generated by Django 6.0.4 on 2026-05-01 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammatch',
            name='match_ptr',
        ),
        migrations.RemoveField(
            model_name='teammatch',
            name='team1_player1',
        ),
        migrations.RemoveField(
            model_name='teammatch',
            name='team1_player2',
        ),
        migrations.RemoveField(
            model_name='teammatch',
            name='team2_player1',
        ),
        migrations.RemoveField(
            model_name='teammatch',
            name='team2_player2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='is_team_match',
        ),
        migrations.AddField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('TEAM', 'Team')], default='TEAM', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='field',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Court 1'), (2, 'Court 2'), (3, 'Court 3'), (4, 'Court 4'), (5, 'Court 5')], null=True),
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(blank=True, choices=[('A', 'Team A'), ('B', 'Team B')], max_length=1, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='matches.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SingleMatch',
        ),
        migrations.DeleteModel(
            name='TeamMatch',
        ),
    ]
