# Generated by Django 6.0.4 on 2026-05-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='points',
        ),
        migrations.AddField(
            model_name='achievement',
            name='imgSrc',
            field=models.URLField(blank=True, null=True),
        ),
    ]
