# Generated by Django 6.0.4 on 2026-05-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_remove_achievement_points_achievement_imgsrc'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='requirement_type',
            field=models.CharField(choices=[('friend_count', 'Friend Count'), ('account_age', 'Account Age'), ('joined_match', 'Joined Match')], default='JOINED_MATCH', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievement',
            name='requirement_value',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievement',
            name='slug',
            field=models.SlugField(default='temp-slug', unique=True),
            preserve_default=False,
        ),
    ]
