# Generated by Django 6.0.4 on 2026-05-02 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_create_achievements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='imgSrc',
            new_name='img_src',
        ),
    ]
